"""empty message

Revision ID: d38cd8af7db7
Revises: 
Create Date: 2017-05-11 22:10:20.487253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38cd8af7db7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('createdDate', sa.DateTime(timezone=True), nullable=True))
    op.add_column('movies', sa.Column('updatedDate', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    #op.add_column('ideas', sa.Column('createdDate', sa.DateTime(timezone=True), nullable=True))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'updatedDate')
    op.drop_column('movies', 'createdDate')
    # ### end Alembic commands ###
